### ISSUE TITLE
Empty Blocks are rendered when Jh_BlockLogger extension is enabled

### ISSUE THREAD

**Issue by marvinhuebner** [WeareJH/m2-module-jh-block-logger#4]
First of all, i would like to thank you for these great extensions. It's really helpful!

As far as i know, the default magento way is when a block is empty, it is not rendered in the frontend. But if we i enable Jh_BlockLogger these blocks were also rendered. This crashes the template sometimes.

Would be great if this extension would note if the block should not be rendered in the frontend.

Here in this example is the `.top-container` rendered, but it has no inner html. If i disable the extension the `.top-container` is not rendered add all.

<img width="1680" alt="vollbild_27_06_18__13_23" src="https://user-images.githubusercontent.com/13386633/41971306-39b8461e-7a0e-11e8-8d5f-d797ea30a3a8.png">

**Comment by danielmaier42** [comment]
I just created a pull request for this issue - it seems quite easy to just don't renter the block annotation when the blocks content is empty. This could lead to containers being rendered even when they (originally) have no content.

See pull request #5
